FROM nvidia/cuda:8.0-cudnn7-devel
RUN apt update -y
Run apt upgrade -y

# Installing OpenCV dependencies
RUN apt install -y \
git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev \
python-dev python-numpy python3-dev python3-numpy python-scipy python3-scipy \
libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev \
libeigen2-dev libeigen3-dev \
cmake

# Clone the OpenCV github repository
WORKDIR /home/
RUN mkdir Github
WORKDIR Github
RUN git clone https://github.com/opencv/opencv.git
WORKDIR opencv

# Create a build folder and pass the correct parameters to CMAKE
# For now we just demand a specific CUDA architecture and TBB as parallell framework
# Finally install everything
RUN mkdir build
WORKDIR build
RUN cmake -DWITH_TBB=ON -DCUDA_ARCH_BIN=6.1 -DCUDA_ARCH_PTX=6.1 -DENABLE_IMPL_COLLECTION=ON -DTBB_ENV_INCLUDE=/usr/include -DTBB_ENV_LIB=/usr/lib/x86_64-linux-gnu/libtbb.so -DTBB_VER_FILE=/usr/include/tbb/tbb_stddef.h ..
RUN make -j $(nproc)
RUN make install
WORKDIR /

# Needed to be able to change small things
# Should be present in the basic docker file
RUN apt install -y vim

CMD /bin/bash

