FROM nvidia/cuda:8.0-cudnn5-devel

# Then reload everything
RUN apt update -y
RUN apt upgrade -y

# Pre-requisites
RUN apt install -y vim git sudo \
libhdf5-serial-dev

# Install scannet
WORKDIR /home/Github
RUN git clone https://github.com/ScanNet/ScanNet

# Make the segmentator application work
WORKDIR /home/Github/ScanNet/Segmentator
RUN make -j $(nproc)

# Install the backend for the object labelling and classification
WORKDIR /
RUN git clone https://github.com/torch/distro.git ~/torch --recursive
WORKDIR /root/torch
RUN bash install-deps
RUN sed -i '4s/.*/BATCH_INSTALL=1/' install.sh
RUN ./install.sh
RUN . ~/.bashrc
RUN /root/torch/install/bin/luarocks install hdf5

# Set back the work directory
WORKDIR /

CMD /bin/bash
